[package]
name = "pigeon"
version = "0.1.0"
description = "Unofficial XChat desktop client"
authors = ["Ilya/Apvcode"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "pigeon_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.11.3", features = [] }
dirs = "6.0"

[target.'cfg(target_os = "linux")'.dependencies]
webkit2gtk = "2.0.2"
